### PR TITLE
added product type

### PR DESCRIPTION
**Pull request by christopherpickering**
I've added product type for the schema. Let me know if there is anything you'd like tweaked. Thanks for the tool!

### CODE REVIEW

**Comment by christopherpickering** [comment]
There are a few warning from schema.org I will fix up, and add the demo file.

**Comment by christopherpickering** [comment]
I think it is all set now. Are you interested in updating the dependencies? the 11ty version is an old one and clashes with other plugins. I updated everything for testing and there were a ton of new messages from the latest linter versions.

**Comment by nunof07** [comment]
Wow, this is awesome. Thank you so much @christopherpickering. Looks great.

Yes, I think it might be a good idea to update the the dependencies. Are the issues in the version due to the peer dependency?

For the sitemap plugin, the version was changed to this: https://github.com/quasibit/eleventy-plugin-sitemap/blob/master/package.json#L80

and it kept compatibility with both versions.

**Comment by christopherpickering** [comment]
Thanks! Yeah, I'll checkout the dependencies sometime.

**Comment by christopherpickering** [comment]
out in the wild it seems to be working!
image

**Comment by nunof07** [comment]
Nice, thanks for sharing.

**Pull request merged**
