### PR TITLE
added fix for #14, #16, added site search to website schema

### PR DESCRIPTION
**Pull request by christopherpickering**
I'm not sure exactly how to text for this, the tests are already passing but probably shouldn't. I think the function `parseEqual` is already stripping null/undefined.

Anyways, this seems to fix it :)

Thanks!

### CODE REVIEW

**Comment by christopherpickering** [comment]
Thanks!

**Comment by nunof07** [comment]
Thank you again. Awesome!

**Comment by nunof07** [comment]
FYI there was a small issue in the demo for search action, but now fixed.

**Comment by christopherpickering** [comment]
Nice, thanks!

**Pull request merged**
