### PR TITLE
update GutHub Actions, and bump package version

### PR DESCRIPTION
**Pull request by reatlat**

### CODE REVIEW

**Comment by reatlat** [comment]
@nunof07 would you please release bumper version to NPN?

**Comment by nunof07** [comment]
@reatlat thank you, appreciate it

**Comment by nunof07** [comment]
@reatlat oh, yes my bad, didn't notice that. The release is triggered by semantic commits.
So we have to write commit messages like this: https://semantic-release.gitbook.io/semantic-release#commit-message-format and shouldn't change the version manually in package.json.
Then semantic-release builds the changelog out of that and determines version increment.
Let me try to fix it, sec.

**Comment by nunof07** [comment]
@reatlat it's showing up for me now in npm: https://www.npmjs.com/package/@quasibit/eleventy-plugin-schema?activeTab=versions

**Pull request merged**
